server:
  port: 8080

spring:
  application:
    name: yolo-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:33306/yolo_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: biroot
    password: e&nD(=AX#NsobZi+0pbr
#    url: jdbc:mysql://localhost:3306/yolo_db?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
#    username: root
#    password: 944c917f2f123957
  jackson:
    time-zone: UTC
    serialization:
      write-dates-as-timestamps: false

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

wechat:
  appid: wxd178ee821696b486
  secret: 144c8b42ecefaefedf1fde88a8fa3c0b
